// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf9DnohYjLFwnXDCtOHerTcuar5BKMwFA',
    appId: '1:828367404664:web:3ae3cc94adbfd72a79f78d',
    messagingSenderId: '828367404664',
    projectId: 'mcproj-479cc',
    authDomain: 'mcproj-479cc.firebaseapp.com',
    storageBucket: 'mcproj-479cc.appspot.com',
    measurementId: 'G-GK9RCXDCC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEUqU6S_6Yfg_es2gxi4TJRuDxAj8Vxdk',
    appId: '1:828367404664:android:177640914063d8f479f78d',
    messagingSenderId: '828367404664',
    projectId: 'mcproj-479cc',
    storageBucket: 'mcproj-479cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnblOs1dssLFbQoryq3pZ6pm3MHUud-9A',
    appId: '1:828367404664:ios:e066a6d2c8ddb53879f78d',
    messagingSenderId: '828367404664',
    projectId: 'mcproj-479cc',
    storageBucket: 'mcproj-479cc.appspot.com',
    iosBundleId: 'com.example.mcproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnblOs1dssLFbQoryq3pZ6pm3MHUud-9A',
    appId: '1:828367404664:ios:8717ce85a344886279f78d',
    messagingSenderId: '828367404664',
    projectId: 'mcproj-479cc',
    storageBucket: 'mcproj-479cc.appspot.com',
    iosBundleId: 'com.example.mcproj.RunnerTests',
  );
}
